title: ANDYMORPHS
author:
  name: Andy Morphs
  email: andymorphs@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  I'm Andy Morphs! I make videos on VR

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: andymorphs
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: andymorphs
    # linkedin: jekyll
    # pinterest: jekyll
    youtube: andymorphs
    tiktok: andymorphs
    # youtube_channel: UCNX88l8ja5flD21ni78ZjVQ
    youtube_channel_name: andymorphs
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
